### ISSUE TITLE
VS Code Debug

### ISSUE THREAD

**Issue by tomdavidson** [ospatil/generator-node-typescript#17]
Thank you for this generator. Do you use VS Code to debug? Mind sharing your .vscode files?

**Comment by ospatil** [comment]
You are welcome. I do use VS Code to debug using the [standard approach](https://code.visualstudio.com/docs/editor/debugging) by generating `launch.json` file from Debug View. 

Here is how my `.vscode/launch.json` file looks like -  

```js
{
  // Use IntelliSense to learn about possible Node.js debug attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Lancer le programme",
      "program": "${workspaceRoot}/lib/index.js",
      "cwd": "${workspaceRoot}"
    },
    {
      "type": "node",
      "request": "attach",
      "name": "Attacher au processus",
      "port": 5858
    }
  ]
}
```

Hope this helps. I'll close this issue now. I see that it would be convenient to the users if the scaffolded project contained a `.vscode/launch.json` file out of the box. I'll add it in the next release.

**Comment by MonsieurMan** [comment]
Hello, just used your generator to relieve me from setting test up for an old project, love it.
Why did you not added the debug setup yet? I can PR something if you want.

**Comment by ospatil** [comment]
I'm glad you found it useful.

Check out the latest [v4.0.0](https://github.com/ospatil/generator-node-typescript/releases/tag/v4.0.0) release. It has launch configurations for debugging current source and test file. You can see little preview at the bottom of landing page 😊.

It uses [Jest](https://facebook.github.io/jest/) as a testing framework now and I heartily recommend it. It makes configuration, testing and coverage a breeze.

**Comment by MonsieurMan** [comment]
Nice ! Thank you for the update and the repo, I'll come back to fork anytime soon.  😄
