### ISSUE TITLE
Test script regex

### ISSUE THREAD

**Issue by charliemc** [ospatil/generator-node-typescript#19]
Hi,

I've generated a project lately and experienced some issues when running the `package.json` test script. I had to add single quotes `'` around the regex in order to make mocha work and dive recursively into deeper directories:

`"test": "npm run build && mocha --compilers ts:ts-node/register --recursive 'src/**/*.spec.ts'"`

So, basically `src/**/*.spec.ts` becomes `'src/**/*.spec.ts'`.

Just saying in case anybody experiences this too!

**Comment by ospatil** [comment]
Are you on windows? I use mac and haven't seen this problem. But I see the single quotes works on mac too so I guess I'll simply make the change in the generator itself.

**Comment by charliemc** [comment]
I am using Mac too! 🙂

**Comment by ospatil** [comment]
Alright 😃, thanks for reporting it. I'll make the change in the coming release which should be soon.

**Comment by charliemc** [comment]
Great! You are welcome 😉
