### ISSUE TITLE
Travis and Coveralls / Codecov

### ISSUE THREAD

**Issue by ValterSantosMatos** [ospatil/generator-node-typescript#22]
Hi there,
First of all really nice module.

This is not a real issue, I just recently used this generator to kickstart a small node module and I quickly added a Travis config and Coveralls to it. If you think that it is a good ideia I will be happy to make a PR with the changes, let me know which code coverage tool you would like to add (Coveralls/Codecov/etc...).

Ty

**Comment by ospatil** [comment]
Thank you for the kind words and the offer to help :). I would appreciate a PR for Travis and Coveralls.

**Comment by ospatil** [comment]
Thank you for the pull request. Released v2.3.0 with the changes.
