### ISSUE TITLE
RunKit fails trying to run this package...

### ISSUE THREAD

**Issue by silverfox1948** [ospatil/generator-node-typescript#28]
Your package looks very useful. I especially like that you claim to be integrated into VS Code. 

There is a link on your NPM page that takes me to RunKit. When I then try to run the sample code in RunKit, it throws an exception stating it can't find the module.

**Comment by ospatil** [comment]
This package won't run in RunKit. It's a yeoman generator that needs to be installed globally on user's computer before using it. RunKit is not a right kind of tool for testing it. Regarding the RunKit link on the npm page - that's something npm adds and is beyond my control.
