### ISSUE TITLE
Feature Request : A new typescript-node-package template within VsCode

### ISSUE THREAD

**Issue by abhi18av** [ospatil/generator-node-typescript#31]
Hi @ospatil 

I find myself using this scaffolding more and more, so I was wondering whether it's possible to have a "Generator-Node-Typescript" package within the VsCode extension ecosystem as well?

I'm new to the editor but so far I've loved the TypeScript and the VsCode :)

**Comment by ospatil** [comment]
That's a good idea. I too am a long time user of VSCode and I love it. It's just that I have no clue whatsoever about extensions. Let me see what I can do.

**Comment by ospatil** [comment]
After having thought about it, a VS Code extension won't add much of value. Even today, running the generator command from within the VS Code using integrated terminal is merely ``Ctrl + ` `` away 🙂.
