### ISSUE TITLE
watch:test not running tests on file change

### ISSUE THREAD

**Issue by GaryB432** [ospatil/generator-node-typescript#34]
I just refreshed my generator and `watch:test` is hanging. 

* npm run watch:test
* see `2 tests passed`
* change and save `greeter-spec.ts` to `... new Greeter("tester");`
* no change in test window
* press `CTRL+c` in test window
* coverage stuff shows in test window
* press `CTRL+c` in test window again
* back to command prompt

this is one of my favorite generators!

**Comment by ospatil** [comment]
I'm glad you liked it :). This is fixed in v3.1.1.
