### ISSUE TITLE
Use typescript strict option

### ISSUE THREAD

**Issue by GaryB432** [ospatil/generator-node-typescript#38]
What do you think about upgrading to TypeScript 2.3 and using the [--strict](https://blog.mariusschulz.com/2017/06/09/typescript-2-3-the-strict-compiler-option) option? I ::heart:: strict code!

**Comment by ospatil** [comment]
Regarding TypeScript version, it already installs the latest available (`2.4.2` as of now) since the version string in generated `package.json` is `^2.0.0`.
Regarding `--strict` option, I'm all for it 👍 .
