### ISSUE TITLE
Change output directory from lib to dist

### ISSUE THREAD

**Issue by MonsieurMan** [ospatil/generator-node-typescript#40]
It bugs me that output directory is called lib when I'm not building a library.  
lib stand for library  
dist stand for distribution  
I'm ready to PR if you're sharing my thoughts. I need #39 to be done first though.

**Comment by GaryB432** [comment]
Not speaking for the maintainer here but I believe the idea behind this generator is in fact to generate a _library_ suitable for npm.

**Comment by MonsieurMan** [comment]
It makes sense. I don't think introducing a --dist flag would be interesting then.

**Comment by ospatil** [comment]
As @GaryB432 said, the idea is to create a Node library. But now that you mentioned it, it seems a bit counterintuitive though. 

Let me look around to find whether I'm the only one using this convention and come to conclusion one way or other. I'll keep this open till then.

**Comment by ospatil** [comment]
Alright, checked quite a few and I think I'm in good company - TypeScript itself, TSlint, uglifyjs and jsdom being some of the examples. So "lib" lives.
