### ISSUE TITLE
Options to disable vs code integration and to use npm not yarn

### ISSUE THREAD

**Issue by simonmeusel** [ospatil/generator-node-typescript#42]

**Comment by ospatil** [comment]
Regarding npm, you can use it even now, no? For the initial installation, it will use yarn if available or fall back to npm. But after that you can use npm if you like. 

Regarding VS Code integration, everything is contained in `.vscode` folder at the root and it's pretty harmless :). You can add it to `.gitignore` to exclude it from version control, just ignore it and let it sit there if you are not using VS Code or simply delete it. 

Is there anything else I'm missing?

**Comment by simonmeusel** [comment]
Thanks for the quick response

I think those config options would not harm, and would make creating of projects easier, which is exactly what yeoman is looking to do. But you're right it is not necessary.
