### ISSUE TITLE
Incorrect coverage report

### ISSUE THREAD

**Issue by hypescript** [ospatil/generator-node-typescript#47]
Apparently, since [version 20 of ts-jest](https://github.com/kulshekhar/ts-jest/pull/200) it is required to add additional configuration to get correct coverage report. Namely, [mapCoverage](https://facebook.github.io/jest/docs/en/configuration.html#mapcoverage-boolean) should be set to true.
https://github.com/kulshekhar/ts-jest/pull/200

**Comment by ospatil** [comment]
Thank you for the investigation and pull request 👍 .

**Comment by hypescript** [comment]
Well, thank you for this great generator of yours!
