### ISSUE TITLE
Invokes wrong 'tsc' on windows with multiple tsc versions

### ISSUE THREAD

**Issue by psulek** [ospatil/generator-node-typescript#7]
On my windows, i have several TypeScript installations manually or automatically(by Visual Studio) installed. I have also installed nodejs global module 'tsc' (typescript).

Problem is when you have tsc.exe in "c:\Program Files (x86)\Microsoft SDKs\TypeScript\1.5\tsc.exe"  together with nodejs global module 'tsc' your gulp task `_build` will invoke tsc.exe (from program files) not nodejs version 'tsc'.

For fix, change: `exec('tsc')` to  `exec('tsc.cmd')` within file `gulpfile.js`.

**Comment by rumit91** [comment]
This got me too. Thanks @psulek!

**Comment by ospatil** [comment]
Thanks for the reporting it guys. I'm not a Windows user and therefore have no way of discovering such very OS-specific bugs. I'm working on the next release currently and will incorporate fix for this in it.

**Comment by ospatil** [comment]
This is fixed in the latest release - v1.0.0. The generator now installs TypeScript as local dev dependency and the gulp prepends _node_modules/.bin_ to _process.env.PATH_ thereby ensuring the local `tsc` is always used.
